<?php

/*
 * This file is part of the FusionCMS application.
 *
 * (c) efelle creative <appdev@efelle.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace App\Fieldtypes;

class CountryFieldtype extends Fieldtype
{
    /**
     * @var string
     */
    public $name = 'Country';

    /**
     * @var string
     */
    public $icon = 'globe-americas';

    /**
     * @var string
     */
    public $description = 'Field to select one or more countries.';

    /**
     * @var string
     */
    public $cast = 'string';

    /**
     * @var array
     */
    public $settings = [
        'multiple' => 0,
    ];

    public $data = [
        'AF' => ['name'=>'Afghanistan', 'native'=>'‫افغانستان'],
        'AX' => ['name'=>'Åland Islands', 'native'=>'Åland'],
        'AL' => ['name'=>'Albania', 'native'=>'Shqipëri'],
        'DZ' => ['name'=>'Algeria', 'native'=>'‫الجزائر'],
        'AS' => ['name'=>'American Samoa', 'native'=>''],
        'AD' => ['name'=>'Andorra', 'native'=>''],
        'AO' => ['name'=>'Angola', 'native'=>''],
        'AI' => ['name'=>'Anguilla', 'native'=>''],
        'AQ' => ['name'=>'Antarctica', 'native'=>''],
        'AG' => ['name'=>'Antigua and Barbuda', 'native'=>''],
        'AR' => ['name'=>'Argentina', 'native'=>''],
        'AM' => ['name'=>'Armenia', 'native'=>'Հայաստան'],
        'AW' => ['name'=>'Aruba', 'native'=>''],
        'AC' => ['name'=>'Ascension Island', 'native'=>''],
        'AU' => ['name'=>'Australia', 'native'=>''],
        'AT' => ['name'=>'Austria', 'native'=>'Österreich'],
        'AZ' => ['name'=>'Azerbaijan', 'native'=>'Azərbaycan'],
        'BS' => ['name'=>'Bahamas', 'native'=>''],
        'BH' => ['name'=>'Bahrain', 'native'=>'‫البحرين'],
        'BD' => ['name'=>'Bangladesh', 'native'=>'বাংলাদেশ'],
        'BB' => ['name'=>'Barbados', 'native'=>''],
        'BY' => ['name'=>'Belarus', 'native'=>'Беларусь'],
        'BE' => ['name'=>'Belgium', 'native'=>'België'],
        'BZ' => ['name'=>'Belize', 'native'=>''],
        'BJ' => ['name'=>'Benin', 'native'=>'Bénin'],
        'BM' => ['name'=>'Bermuda', 'native'=>''],
        'BT' => ['name'=>'Bhutan', 'native'=>'འབྲུག'],
        'BO' => ['name'=>'Bolivia', 'native'=>''],
        'BA' => ['name'=>'Bosnia and Herzegovina', 'native'=>'Босна и Херцеговина'],
        'BW' => ['name'=>'Botswana', 'native'=>''],
        'BV' => ['name'=>'Bouvet Island', 'native'=>''],
        'BR' => ['name'=>'Brazil', 'native'=>'Brasil'],
        'IO' => ['name'=>'British Indian Ocean Territory', 'native'=>''],
        'VG' => ['name'=>'British Virgin Islands', 'native'=>''],
        'BN' => ['name'=>'Brunei', 'native'=>''],
        'BG' => ['name'=>'Bulgaria', 'native'=>'България'],
        'BF' => ['name'=>'Burkina Faso', 'native'=>''],
        'BI' => ['name'=>'Burundi', 'native'=>'Uburundi'],
        'KH' => ['name'=>'Cambodia', 'native'=>'កម្ពុជា'],
        'CM' => ['name'=>'Cameroon', 'native'=>'Cameroun'],
        'CA' => ['name'=>'Canada', 'native'=>''],
        'IC' => ['name'=>'Canary Islands', 'native'=>'islas Canarias'],
        'CV' => ['name'=>'Cape Verde', 'native'=>'Kabu Verdi'],
        'BQ' => ['name'=>'Caribbean Netherlands', 'native'=>''],
        'KY' => ['name'=>'Cayman Islands', 'native'=>''],
        'CF' => ['name'=>'Central African Republic', 'native'=>'République centrafricaine'],
        'EA' => ['name'=>'Ceuta and Melilla', 'native'=>'Ceuta y Melilla'],
        'TD' => ['name'=>'Chad', 'native'=>'Tchad'],
        'CL' => ['name'=>'Chile', 'native'=>''],
        'CN' => ['name'=>'China', 'native'=>'中国'],
        'CX' => ['name'=>'Christmas Island', 'native'=>''],
        'CP' => ['name'=>'Clipperton Island', 'native'=>''],
        'CC' => ['name'=>'Cocos (Keeling) Islands', 'native'=>'Kepulauan Cocos (Keeling)'],
        'CO' => ['name'=>'Colombia', 'native'=>''],
        'KM' => ['name'=>'Comoros', 'native'=>'‫جزر القمر'],
        'CD' => ['name'=>'Congo (DRC)', 'native'=>'Jamhuri ya Kidemokrasia ya Kongo'],
        'CG' => ['name'=>'Congo (Republic)', 'native'=>'Congo-Brazzaville'],
        'CK' => ['name'=>'Cook Islands', 'native'=>''],
        'CR' => ['name'=>'Costa Rica', 'native'=>''],
        'CI' => ['name'=>'Côte d’Ivoire', 'native'=>''],
        'HR' => ['name'=>'Croatia', 'native'=>'Hrvatska'],
        'CU' => ['name'=>'Cuba', 'native'=>''],
        'CW' => ['name'=>'Curaçao', 'native'=>''],
        'CY' => ['name'=>'Cyprus', 'native'=>'Κύπρος'],
        'CZ' => ['name'=>'Czech Republic', 'native'=>'Česká republika'],
        'DK' => ['name'=>'Denmark', 'native'=>'Danmark'],
        'DG' => ['name'=>'Diego Garcia', 'native'=>''],
        'DJ' => ['name'=>'Djibouti', 'native'=>''],
        'DM' => ['name'=>'Dominica', 'native'=>''],
        'DO' => ['name'=>'Dominican Republic', 'native'=>'República Dominicana'],
        'EC' => ['name'=>'Ecuador', 'native'=>''],
        'EG' => ['name'=>'Egypt', 'native'=>'‫مصر'],
        'SV' => ['name'=>'El Salvador', 'native'=>''],
        'GQ' => ['name'=>'Equatorial Guinea', 'native'=>'Guinea Ecuatorial'],
        'ER' => ['name'=>'Eritrea', 'native'=>''],
        'EE' => ['name'=>'Estonia', 'native'=>'Eesti'],
        'ET' => ['name'=>'Ethiopia', 'native'=>''],
        'FK' => ['name'=>'Falkland Islands', 'native'=>'Islas Malvinas'],
        'FO' => ['name'=>'Faroe Islands', 'native'=>'Føroyar'],
        'FJ' => ['name'=>'Fiji', 'native'=>''],
        'FI' => ['name'=>'Finland', 'native'=>'Suomi'],
        'FR' => ['name'=>'France', 'native'=>''],
        'GF' => ['name'=>'French Guiana', 'native'=>'Guyane française'],
        'PF' => ['name'=>'French Polynesia', 'native'=>'Polynésie française'],
        'TF' => ['name'=>'French Southern Territories', 'native'=>'Terres australes françaises'],
        'GA' => ['name'=>'Gabon', 'native'=>''],
        'GM' => ['name'=>'Gambia', 'native'=>''],
        'GE' => ['name'=>'Georgia', 'native'=>'საქართველო'],
        'DE' => ['name'=>'Germany', 'native'=>'Deutschland'],
        'GH' => ['name'=>'Ghana', 'native'=>'Gaana'],
        'GI' => ['name'=>'Gibraltar', 'native'=>''],
        'GR' => ['name'=>'Greece', 'native'=>'Ελλάδα'],
        'GL' => ['name'=>'Greenland', 'native'=>'Kalaallit Nunaat'],
        'GD' => ['name'=>'Grenada', 'native'=>''],
        'GP' => ['name'=>'Guadeloupe', 'native'=>''],
        'GU' => ['name'=>'Guam', 'native'=>''],
        'GT' => ['name'=>'Guatemala', 'native'=>''],
        'GG' => ['name'=>'Guernsey', 'native'=>''],
        'GN' => ['name'=>'Guinea', 'native'=>'Guinée'],
        'GW' => ['name'=>'Guinea-Bissau', 'native'=>'Guiné Bissau'],
        'GY' => ['name'=>'Guyana', 'native'=>''],
        'HT' => ['name'=>'Haiti', 'native'=>''],
        'HM' => ['name'=>'Heard & McDonald Islands', 'native'=>''],
        'HN' => ['name'=>'Honduras', 'native'=>''],
        'HK' => ['name'=>'Hong Kong', 'native'=>'香港'],
        'HU' => ['name'=>'Hungary', 'native'=>'Magyarország'],
        'IS' => ['name'=>'Iceland', 'native'=>'Ísland'],
        'IN' => ['name'=>'India', 'native'=>'भारत'],
        'ID' => ['name'=>'Indonesia', 'native'=>''],
        'IR' => ['name'=>'Iran', 'native'=>'‫ایران'],
        'IQ' => ['name'=>'Iraq', 'native'=>'‫العراق'],
        'IE' => ['name'=>'Ireland', 'native'=>''],
        'IM' => ['name'=>'Isle of Man', 'native'=>''],
        'IL' => ['name'=>'Israel', 'native'=>'‫ישראל'],
        'IT' => ['name'=>'Italy', 'native'=>'Italia'],
        'JM' => ['name'=>'Jamaica', 'native'=>''],
        'JP' => ['name'=>'Japan', 'native'=>'日本'],
        'JE' => ['name'=>'Jersey', 'native'=>''],
        'JO' => ['name'=>'Jordan', 'native'=>'‫الأردن'],
        'KZ' => ['name'=>'Kazakhstan', 'native'=>'Казахстан'],
        'KE' => ['name'=>'Kenya', 'native'=>''],
        'KI' => ['name'=>'Kiribati', 'native'=>''],
        'XK' => ['name'=>'Kosovo', 'native'=>'Kosovë'],
        'KW' => ['name'=>'Kuwait', 'native'=>'‫الكويت'],
        'KG' => ['name'=>'Kyrgyzstan', 'native'=>'Кыргызстан'],
        'LA' => ['name'=>'Laos', 'native'=>'ລາວ'],
        'LV' => ['name'=>'Latvia', 'native'=>'Latvija'],
        'LB' => ['name'=>'Lebanon', 'native'=>'‫لبنان'],
        'LS' => ['name'=>'Lesotho', 'native'=>''],
        'LR' => ['name'=>'Liberia', 'native'=>''],
        'LY' => ['name'=>'Libya', 'native'=>'‫ليبيا'],
        'LI' => ['name'=>'Liechtenstein', 'native'=>''],
        'LT' => ['name'=>'Lithuania', 'native'=>'Lietuva'],
        'LU' => ['name'=>'Luxembourg', 'native'=>''],
        'MO' => ['name'=>'Macau', 'native'=>'澳門'],
        'MK' => ['name'=>'Macedonia (FYROM)', 'native'=>'Македонија'],
        'MG' => ['name'=>'Madagascar', 'native'=>'Madagasikara'],
        'MW' => ['name'=>'Malawi', 'native'=>''],
        'MY' => ['name'=>'Malaysia', 'native'=>''],
        'MV' => ['name'=>'Maldives', 'native'=>''],
        'ML' => ['name'=>'Mali', 'native'=>''],
        'MT' => ['name'=>'Malta', 'native'=>''],
        'MH' => ['name'=>'Marshall Islands', 'native'=>''],
        'MQ' => ['name'=>'Martinique', 'native'=>''],
        'MR' => ['name'=>'Mauritania', 'native'=>'‫موريتانيا'],
        'MU' => ['name'=>'Mauritius', 'native'=>'Moris'],
        'YT' => ['name'=>'Mayotte', 'native'=>''],
        'MX' => ['name'=>'Mexico', 'native'=>''],
        'FM' => ['name'=>'Micronesia', 'native'=>''],
        'MD' => ['name'=>'Moldova', 'native'=>'Republica Moldova'],
        'MC' => ['name'=>'Monaco', 'native'=>''],
        'MN' => ['name'=>'Mongolia', 'native'=>'Монгол'],
        'ME' => ['name'=>'Montenegro', 'native'=>'Crna Gora'],
        'MS' => ['name'=>'Montserrat', 'native'=>''],
        'MA' => ['name'=>'Morocco', 'native'=>'‫المغرب'],
        'MZ' => ['name'=>'Mozambique', 'native'=>'Moçambique'],
        'MM' => ['name'=>'Myanmar (Burma)', 'native'=>'မြန်မာ'],
        'NA' => ['name'=>'Namibia', 'native'=>'Namibië'],
        'NR' => ['name'=>'Nauru', 'native'=>''],
        'NP' => ['name'=>'Nepal', 'native'=>'नेपाल'],
        'NL' => ['name'=>'Netherlands', 'native'=>'Nederland'],
        'NC' => ['name'=>'New Caledonia', 'native'=>'Nouvelle-Calédonie'],
        'NZ' => ['name'=>'New Zealand', 'native'=>''],
        'NI' => ['name'=>'Nicaragua', 'native'=>''],
        'NE' => ['name'=>'Niger', 'native'=>'Nijar'],
        'NG' => ['name'=>'Nigeria', 'native'=>''],
        'NU' => ['name'=>'Niue', 'native'=>''],
        'NF' => ['name'=>'Norfolk Island', 'native'=>''],
        'MP' => ['name'=>'Northern Mariana Islands', 'native'=>''],
        'KP' => ['name'=>'North Korea', 'native'=>'조선 민주주의 인민 공화국'],
        'NO' => ['name'=>'Norway', 'native'=>'Norge'],
        'OM' => ['name'=>'Oman', 'native'=>'‫عُمان'],
        'PK' => ['name'=>'Pakistan', 'native'=>'‫پاکستان'],
        'PW' => ['name'=>'Palau', 'native'=>''],
        'PS' => ['name'=>'Palestine', 'native'=>'‫فلسطين'],
        'PA' => ['name'=>'Panama', 'native'=>''],
        'PG' => ['name'=>'Papua New Guinea', 'native'=>''],
        'PY' => ['name'=>'Paraguay', 'native'=>''],
        'PE' => ['name'=>'Peru', 'native'=>'Perú'],
        'PH' => ['name'=>'Philippines', 'native'=>''],
        'PN' => ['name'=>'Pitcairn Islands', 'native'=>''],
        'PL' => ['name'=>'Poland', 'native'=>'Polska'],
        'PT' => ['name'=>'Portugal', 'native'=>''],
        'PR' => ['name'=>'Puerto Rico', 'native'=>''],
        'QA' => ['name'=>'Qatar', 'native'=>'‫قطر'],
        'RE' => ['name'=>'Réunion', 'native'=>'La Réunion'],
        'RO' => ['name'=>'Romania', 'native'=>'România'],
        'RU' => ['name'=>'Russia', 'native'=>'Россия'],
        'RW' => ['name'=>'Rwanda', 'native'=>''],
        'BL' => ['name'=>'Saint Barthélemy', 'native'=>'Saint-Barthélemy'],
        'SH' => ['name'=>'Saint Helena', 'native'=>''],
        'KN' => ['name'=>'Saint Kitts and Nevis', 'native'=>''],
        'LC' => ['name'=>'Saint Lucia', 'native'=>''],
        'MF' => ['name'=>'Saint Martin', 'native'=>''],
        'PM' => ['name'=>'Saint Pierre and Miquelon', 'native'=>'Saint-Pierre-et-Miquelon'],
        'WS' => ['name'=>'Samoa', 'native'=>''],
        'SM' => ['name'=>'San Marino', 'native'=>''],
        'ST' => ['name'=>'São Tomé and Príncipe', 'native'=>'São Tomé e Príncipe'],
        'SA' => ['name'=>'Saudi Arabia', 'native'=>'‫المملكة العربية السعودية'],
        'SN' => ['name'=>'Senegal', 'native'=>'Sénégal'],
        'RS' => ['name'=>'Serbia', 'native'=>'Србија'],
        'SC' => ['name'=>'Seychelles', 'native'=>''],
        'SL' => ['name'=>'Sierra Leone', 'native'=>''],
        'SG' => ['name'=>'Singapore', 'native'=>''],
        'SX' => ['name'=>'Sint Maarten', 'native'=>''],
        'SK' => ['name'=>'Slovakia', 'native'=>'Slovensko'],
        'SI' => ['name'=>'Slovenia', 'native'=>'Slovenija'],
        'SB' => ['name'=>'Solomon Islands', 'native'=>''],
        'SO' => ['name'=>'Somalia', 'native'=>'Soomaaliya'],
        'ZA' => ['name'=>'South Africa', 'native'=>''],
        'GS' => ['name'=>'South Georgia & South Sandwich Islands', 'native'=>''],
        'KR' => ['name'=>'South Korea', 'native'=>'대한민국'],
        'SS' => ['name'=>'South Sudan', 'native'=>'‫جنوب السودان'],
        'ES' => ['name'=>'Spain', 'native'=>'España'],
        'LK' => ['name'=>'Sri Lanka', 'native'=>'ශ්‍රී ලංකාව'],
        'VC' => ['name'=>'St. Vincent & Grenadines', 'native'=>''],
        'SD' => ['name'=>'Sudan', 'native'=>'‫السودان'],
        'SR' => ['name'=>'Suriname', 'native'=>''],
        'SJ' => ['name'=>'Svalbard and Jan Mayen', 'native'=>'Svalbard og Jan Mayen'],
        'SZ' => ['name'=>'Swaziland', 'native'=>''],
        'SE' => ['name'=>'Sweden', 'native'=>'Sverige'],
        'CH' => ['name'=>'Switzerland', 'native'=>'Schweiz'],
        'SY' => ['name'=>'Syria', 'native'=>'‫سوريا'],
        'TW' => ['name'=>'Taiwan', 'native'=>'台灣'],
        'TJ' => ['name'=>'Tajikistan', 'native'=>''],
        'TZ' => ['name'=>'Tanzania', 'native'=>''],
        'TH' => ['name'=>'Thailand', 'native'=>'ไทย'],
        'TL' => ['name'=>'Timor-Leste', 'native'=>''],
        'TG' => ['name'=>'Togo', 'native'=>''],
        'TK' => ['name'=>'Tokelau', 'native'=>''],
        'TO' => ['name'=>'Tonga', 'native'=>''],
        'TT' => ['name'=>'Trinidad and Tobago', 'native'=>''],
        'TA' => ['name'=>'Tristan da Cunha', 'native'=>''],
        'TN' => ['name'=>'Tunisia', 'native'=>'‫تونس'],
        'TR' => ['name'=>'Turkey', 'native'=>'Türkiye'],
        'TM' => ['name'=>'Turkmenistan', 'native'=>''],
        'TC' => ['name'=>'Turks and Caicos Islands', 'native'=>''],
        'TV' => ['name'=>'Tuvalu', 'native'=>''],
        'UM' => ['name'=>'U.S. Outlying Islands', 'native'=>''],
        'VI' => ['name'=>'U.S. Virgin Islands', 'native'=>''],
        'UG' => ['name'=>'Uganda', 'native'=>''],
        'UA' => ['name'=>'Ukraine', 'native'=>'Україна'],
        'AE' => ['name'=>'United Arab Emirates', 'native'=>'‫الإمارات العربية المتحدة'],
        'GB' => ['name'=>'United Kingdom', 'native'=>''],
        'US' => ['name'=>'United States', 'native'=>''],
        'UY' => ['name'=>'Uruguay', 'native'=>''],
        'UZ' => ['name'=>'Uzbekistan', 'native'=>'Oʻzbekiston'],
        'VU' => ['name'=>'Vanuatu', 'native'=>''],
        'VA' => ['name'=>'Vatican City', 'native'=>'Città del Vaticano'],
        'VE' => ['name'=>'Venezuela', 'native'=>''],
        'VN' => ['name'=>'Vietnam', 'native'=>'Việt Nam'],
        'WF' => ['name'=>'Wallis and Futuna', 'native'=>''],
        'EH' => ['name'=>'Western Sahara', 'native'=>'‫الصحراء الغربية'],
        'YE' => ['name'=>'Yemen', 'native'=>'‫اليمن'],
        'ZM' => ['name'=>'Zambia', 'native'=>''],
        'ZW' => ['name'=>'Zimbabwe', 'native'=>'']
    ];

    /**
     * @var array
     */
    public $column = [
        'type' => 'string',
    ];
}
